### Amazon product reviews: Model Building: Building various Models

In [1]:
import os
os.getcwd()

'/Users/dhanasreedevi/Desktop/EXcelr_Complete_Amazon_review_Project/3. Model_building'

'/Users/dhanasreedevi/Desktop/EXcelr_Complete_Amazon_review_Project/3. Model_building'

In [2]:
os.chdir('/Users/dhanasreedevi/Desktop/EXcelr_Complete_Amazon_review_Project/3. Model_building')

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#from mlxtend.plotting import plot_learning_curves

In [4]:
df = pd.read_excel('review_labels.xlsx')
df.head()

Unnamed: 0                                            reviews label
0           0  would say best available mic price range mic c...   pos
1           1  hi using mic month writing review give genuine...   pos
2           2  recording phone laptop quality get regular hea...   pos
3           3  stoped working within months recording startin...   neu
4           4  give honest review boya read full may help cle...   pos

Unnamed: 0                                            reviews label
0           0  would say best available mic price range mic c...   pos
1           1  hi using mic month writing review give genuine...   pos
2           2  recording phone laptop quality get regular hea...   pos
3           3  stoped working within months recording startin...   neu
4           4  give honest review boya read full may help cle...   pos

In [5]:
#val=pd.read_excel('Amazon_labels_val.xlsx')

In [6]:
print(df.shape)
#print(val.shape)

(1000, 3)
(1000, 3)


In [7]:
#rev_val=val.drop('label',axis=1)
#rev_val.shape

In [8]:
#rev_val.head()

In [9]:
df['label'].value_counts()

pos    761
neg    196
neu     43
Name: label, dtype: int64

pos    761
neg    196
neu     43
Name: label, dtype: int64

### Check for missing values

In [10]:
df.isnull().sum()

Unnamed: 0    0
reviews       2
label         0
dtype: int64

Unnamed: 0    0
reviews       2
label         0
dtype: int64

In [11]:
df.dropna(inplace=True)

df.shape

(998, 3)

(998, 3)

In [12]:
from sklearn.model_selection import train_test_split
X = df['reviews']
y = df['label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

## using Pipeline for vectorization and model building

In [13]:
# imporing pipeline and model libraries
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer

In [14]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

In [15]:
# Naïve Bayes Pipeline:
text_clf_Mnb = Pipeline([('tfidf', TfidfVectorizer(ngram_range=(1, 1))),
                     ('clf', MultinomialNB()),])
                        
# Linear SVC Pipeline:
text_clf_lsvc = Pipeline([('tfidf', TfidfVectorizer(ngram_range=(1, 1))),
                     ('clf', LinearSVC()),])

## <font> <font color="green" > Model 1: MultinomialNB

In [16]:
text_clf_Mnb.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [17]:
# Form a prediction set
predictions = text_clf_Mnb.predict(X_test)

In [18]:
predictions

array(['pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos',

array(['pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos',
       'pos', 'pos',

In [19]:
# Report the confusion matrix
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[  0   0  61]
 [  0   0  10]
 [  0   0 259]]
[[  0   0  61]
 [  0   0  10]
 [  0   0 259]]


In [20]:
# Print a classification report
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

         neg       0.00      0.00      0.00        61
         neu       0.00      0.00      0.00        10
         pos       0.78      1.00      0.88       259

    accuracy                           0.78       330
   macro avg       0.26      0.33      0.29       330
weighted avg       0.62      0.78      0.69       330

              precision    recall  f1-score   support

         neg       0.00      0.00      0.00        61
         neu       0.00      0.00      0.00        10
         pos       0.78      1.00      0.88       259

    accuracy                           0.78       330
   macro avg       0.26      0.33      0.29       330
weighted avg       0.62      0.78      0.69       330



/Users/dhanasreedevi/opt/anaconda3/envs/Virtual_env/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/dhanasreedevi/opt/anaconda3/envs/Virtual_env/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/dhanasreedevi/opt/anaconda3/envs/Virtual_env/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

In [21]:
print(metrics.accuracy_score(y_test,predictions))

0.7848484848484848
0.7848484848484848


In [26]:
text1="good to see you"

In [27]:
print(text_clf_Mnb.predict([text1]))

['pos']
['pos']


## <font> <font color="green" > Model 2: Linear SVC

In [28]:
text_clf_lsvc.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', LinearSVC())])

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', LinearSVC())])

In [30]:
# Form a prediction set
predictions = text_clf_lsvc.predict(X_test)

In [31]:
# Report the confusion matrix
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[ 39   0  22]
 [  0   1   9]
 [ 10   1 248]]
[[ 39   0  22]
 [  0   1   9]
 [ 10   1 248]]


In [32]:
# Print a classification report
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

         neg       0.80      0.64      0.71        61
         neu       0.50      0.10      0.17        10
         pos       0.89      0.96      0.92       259

    accuracy                           0.87       330
   macro avg       0.73      0.57      0.60       330
weighted avg       0.86      0.87      0.86       330

              precision    recall  f1-score   support

         neg       0.80      0.64      0.71        61
         neu       0.50      0.10      0.17        10
         pos       0.89      0.96      0.92       259

    accuracy                           0.87       330
   macro avg       0.73      0.57      0.60       330
weighted avg       0.86      0.87      0.86       330



In [33]:
# Print the overall accuracy
print(metrics.accuracy_score(y_test,predictions))

0.8727272727272727
0.8727272727272727


In [34]:
print(text_clf_lsvc.predict([text1]))


['pos']
['pos']


## <font> <font color="green" > Model 3:Decision Tree Classifier 

In [35]:
from sklearn.tree import DecisionTreeClassifier

In [36]:
text_clf_Dt = Pipeline([('tfidf', TfidfVectorizer(ngram_range=(1, 1))),
                     ('clf',DecisionTreeClassifier()),
])

In [37]:
text_clf_Dt.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('clf', DecisionTreeClassifier())])

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('clf', DecisionTreeClassifier())])

In [38]:
predictions = text_clf_Dt.predict(X_test)

In [39]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[ 34   0  27]
 [  3   1   6]
 [ 31   8 220]]
[[ 34   0  27]
 [  3   1   6]
 [ 31   8 220]]


In [40]:
print(metrics.accuracy_score(y_test,predictions))

0.7727272727272727
0.7727272727272727


In [41]:
print(text_clf_Dt.predict([text1]))


['pos']
['pos']


### <font> <font color="green" > Model 4:  Random Forest Classifier

In [42]:
from sklearn.ensemble import RandomForestClassifier

In [43]:
text_clf_Rf = Pipeline([('tfidf', TfidfVectorizer(ngram_range=(1, 1))),
                     ('clf',RandomForestClassifier()),
])

In [44]:
text_clf_Rf.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('clf', RandomForestClassifier())])

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('clf', RandomForestClassifier())])

In [45]:
predictions = text_clf_Rf.predict(X_test)

In [46]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[ 25   0  36]
 [  0   1   9]
 [  9   0 250]]
[[ 25   0  36]
 [  0   1   9]
 [  9   0 250]]


In [47]:
print(metrics.accuracy_score(y_test,predictions))

0.8363636363636363
0.8363636363636363


In [48]:
print(text_clf_Rf.predict([text1]))

['pos']
['pos']


 ## <font> <font color="green" > Model 5: XGboost Classifier


In [49]:
from xgboost import XGBClassifier

In [50]:
text_clf_xgb = Pipeline([('tfidf', TfidfVectorizer(ngram_range=(1,1))),
                     ('clf', XGBClassifier()),])

In [51]:
text_clf_xgb

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('clf',
                 XGBClassifier(base_score=None, booster=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None, gamma=None, gpu_id=None,
                               importance_type='gain',
                               interaction_constraints=None, learning_rate=None,
                               max_delta_step=None, max_depth=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, n_estimators=100,
                               n_jobs=None, num_parallel_tree=None,
                               random_state=None, reg_alpha=None,
                               reg_lambda=None, scale_pos_weight=None,
                               subsample=None, tree_method=None,
                               validate_parameters=None, verbosity=None))])

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('clf',
                 XGBClassifier(base_score=None, booster=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None, gamma=None, gpu_id=None,
                               importance_type='gain',
                               interaction_constraints=None, learning_rate=None,
                               max_delta_step=None, max_depth=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, n_estimators=100,
                               n_jobs=None, num_parallel_tree=None,
                               random_state=None, reg_alpha=None,
                               reg_lambda=None, scale_pos_weight=None,
                               subsample=None, tree_method=None,
                               validate_parameters=None, verbosity=None))])

In [52]:
text_clf_xgb.fit(X_train, y_train)

/Users/dhanasreedevi/opt/anaconda3/envs/Virtual_env/lib/python3.8/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/dhanasreedevi/opt/anaconda3/envs/Virtual_env/lib/python3.8/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[12:48:21] WARNING: ../src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[12:48:21] WARNING: ../src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('clf',
                 XGBClassifier(base_score=0.5, booster='gbtree',
                               colsample_bylevel=1, colsample_bynode=1,
                               colsample_bytree=1, gamma=0, gpu_id=-1,
                               importance_type='gain',
                               interaction_constraints='',
                               learning_rate=0.300000012, max_delta_step=0,
                               max_depth=6, min_child_weight=1, missing=nan,
                               monotone_constraints='()', n_estimators=100,
                               n_jobs=4, num_parallel_tree=1,
                               objective='multi:softprob', random_state=0,
                               reg_alpha=0, reg_lambda=1, scale_pos_weight=None,
                               subsample=1, tree_method='exact',
                               validate_parameters=1, verbosity=None))])

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('clf',
                 XGBClassifier(base_score=0.5, booster='gbtree',
                               colsample_bylevel=1, colsample_bynode=1,
                               colsample_bytree=1, gamma=0, gpu_id=-1,
                               importance_type='gain',
                               interaction_constraints='',
                               learning_rate=0.300000012, max_delta_step=0,
                               max_depth=6, min_child_weight=1, missing=nan,
                               monotone_constraints='()', n_estimators=100,
                               n_jobs=4, num_parallel_tree=1,
                               objective='multi:softprob', random_state=0,
                               reg_alpha=0, reg_lambda=1, scale_pos_weight=None,
                               subsample=1, tree_method='exact',
                               validate_parameters=1, verbosity=None))])

In [53]:
predictions = text_clf_xgb.predict(X_test)

In [54]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[ 33   0  28]
 [  2   2   6]
 [ 15   1 243]]
[[ 33   0  28]
 [  2   2   6]
 [ 15   1 243]]


In [55]:
print(metrics.accuracy_score(y_test,predictions))

0.8424242424242424
0.8424242424242424


In [57]:
print(text_clf_xgb.predict([text1]))


['pos']
['pos']


 ## <font> <font color="green" > Model 6: SGD


In [58]:
from sklearn.linear_model import SGDClassifier

In [59]:
text_clf_sgd = Pipeline([('tfidf', TfidfVectorizer(ngram_range=(1,1),norm=None,stop_words='english')),
                     ('clf', SGDClassifier()),])

In [60]:
text_clf_sgd.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer(norm=None, stop_words='english')),
                ('clf', SGDClassifier())])

Pipeline(steps=[('tfidf', TfidfVectorizer(norm=None, stop_words='english')),
                ('clf', SGDClassifier())])

In [61]:
predictions = text_clf_sgd.predict(X_test)

In [62]:
print(metrics.accuracy_score(y_test,predictions))

0.8484848484848485
0.8484848484848485


 ## <font> <font color="green" > Model 7: GradientBoostingClassifier


In [63]:
# gradientboosting classifier
from sklearn.ensemble import GradientBoostingClassifier

In [64]:
text_clf_GBC = Pipeline([('tfidf', TfidfVectorizer(ngram_range=(1,1),norm=None,stop_words='english')),
                     ('clf', GradientBoostingClassifier(n_estimators=100,learning_rate=0.5, max_depth=3, random_state=0)),])

In [65]:
text_clf_GBC.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer(norm=None, stop_words='english')),
                ('clf',
                 GradientBoostingClassifier(learning_rate=0.5,
                                            random_state=0))])

Pipeline(steps=[('tfidf', TfidfVectorizer(norm=None, stop_words='english')),
                ('clf',
                 GradientBoostingClassifier(learning_rate=0.5,
                                            random_state=0))])

In [66]:
predictions = text_clf_GBC.predict(X_test)

In [67]:
print(metrics.accuracy_score(y_test,predictions))

0.8151515151515152
0.8151515151515152


In [69]:
print(text_clf_GBC.predict([text1]))


['pos']
['pos']


In [ ]:
   ##################